FROM node:18-alpine

# Create App Directory
WORKDIR /app

# Install Dependencies
COPY package.json .

# Copy app source code
COPY . .

#RUN npm install
RUN npm install

# Build the React app
#RUN npm run build


# Exports
EXPOSE 3000

# Set up a default command
CMD [ "npm","run", "build" ]